---
# Install and configure target ruby version using 'rvm'

- name: Install rvm dependencies from apt
  become: true
  apt:
    state: latest
    install_recommends: no
    name:
      - curl
      - sudo
      - libcurl4-openssl-dev # undeclared/missing dependency for curb gem

- name: Fetch rvm.io PGP keys
  command: gpg --keyserver hkps://hkps.pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
  # TODO should pin CA?

- name: Make GPG -trust- the keys.
  command: gpg --batch --import-ownertrust <<<$'7D2BAF1CF37B13E2069D6956105BD0E739499BDB:5:\n409B6B1796C275462A1703113804BB82D39DC0E3:5:'

- name: Fetch rvm.io install script
  get_url:
    url: https://raw.githubusercontent.com/rvm/rvm/master/binscripts/rvm-installer
    dest: rvm-installer
    mode: u=rx

- name: Fetch rvm.io install script SIGNATURE
  get_url:
    url: https://raw.githubusercontent.com/rvm/rvm/master/binscripts/rvm-installer.asc
    dest: rvm-installer.asc
    mode: u=rx

- name: Verify rvm.io install script SIGNATURE
  command: gpg --batch --verify rvm-installer.asc rvm-installer

# TODO should probably run this as root (with become: true), and then figure out how to make rvm install itself into the user's profile instead)
- name: Install rvm
  command: bash rvm-installer

- name: install target ruby version
  command: rvm install {{ ruby_version }}

- name: enable target ruby version
  command: rvm alias create default {{ ruby_version }}

- name: ensure target ruby version is being used
  command: bash -lc 'ruby -v | fgrep --line-regexp {{ ruby_version }}'

- name: install bundler
  command: bash -lc 'gem install bundler'
