---
# https://gist.github.com/marktheunissen/2979474

- name: LookingGlass - Install apt/package dependencies
  become: true
  apt:
    state: latest
    install_recommends: no
    cache_valid_time: 7200
    update_cache: yes
    name:
      - ca-certificates
      - git
      - tmux
      - libmagic-dev # required by ruby-filemagic
      - apt-transport-https # for: elasticsearch
      - ruby-sass # for compiling themes

- name: Fetch LookingGlass source code
  register: lookingglass
  async: 3600
  poll: 10
  git:
    depth: 1
    dest: LookingGlass
    repo: https://github.com/TransparencyToolkit/LookingGlass.git
    version: editable # aka git branch
    umask: "0077"
    recursive: no
    track_submodules: no

# TODO split out to a load-test-data role
- name: Fetch Test-Data repository
  register: testdata
  async: 3600
  poll: 10
  git:
    depth: 1
    dest: Test-Data
    repo: https://github.com/TransparencyToolkit/Test-Data.git
    umask: "0077"

- name: LG - bundle install
  become: yes
  command: chdir=LookingGlass bash -lc 'bundle install'

- name: Install LG service
  become: true
  template:
    src: lookingglass.service.j2
    dest: /lib/systemd/system/lookingglass.service
    mode: 0444 #ugo=r

- name: Creates lookingglass.service.d directory
  become: true
  file: path=/etc/systemd/system/lookingglass.service.d/ state=directory

- name: generate SECRET_KEY_BASE
  shell: "xxd -ps -l 20 /dev/urandom"
  register: lg_secret_key_base_fh

- name: set environment variables in systemd conf
  become: true
  blockinfile:
    create: yes
    mode: 0440 # ug=r,o=
    dest: /etc/systemd/system/lookingglass.service.d/{{ item.name }}.conf
    content: |
      [Service]
      Environment="{{item.name}}={{ item.value }}"
  with_items:
    - {name: 'SECRET_KEY_BASE', value: '{{ lg_secret_key_base_fh.stdout }}' }
    - {name: 'PROJECT_INDEX', value: '{{ project_index }}' }
    - {name: 'DOCMANAGER_URL', value: '{{ docmanager_url }}' }
    - {name: 'CATALYST_URL', value: '{{ catalyst_url }}'}
    - {name: 'DOCUPLOAD_URL', value: '{{ docupload_url }}'}


- name: Stop LG systemd service
  become: true
  systemd:
    state: stopped
    daemon_reload: yes
    name: lookingglass

- name: LG - Generate simple form data
  command: chdir=LookingGlass bash -lc 'rails generate simple_form:install --bootstrap'
  # TODO creates?

- name: LG - precompile assets
  command: chdir=LookingGlass bash -lc 'rake assets:precompile'

- name: LG - compile themes
  command: chdir=LookingGlass bash -lc './themes.sh -b'

- name: Ensure LG service has started
  become: true
  service: name=lookingglass state=started enabled=yes
