---
# https://gist.github.com/marktheunissen/2979474

- name: LookingGlass - Install apt/package dependencies
  become: true
  apt:
    state: latest
    install_recommends: no
    name:
      - ca-certificates
      - git
      - tmux
      - libmagic-dev # required by ruby-filemagic
      - apt-transport-https # for: elasticsearch

- name: Fetch LookingGlass source code
  register: lookingglass
  async: 3600
  poll: 10
  git:
    force: yes # TODO
    depth: 1
    dest: LookingGlass
    repo: https://github.com/TransparencyToolkit/LookingGlass.git
    umask: "0077"
    recursive: no
    track_submodules: no

# TODO split out to a load-test-data role
- name: Fetch Test-Data repository
  register: testdata
  async: 3600
  poll: 10
  git:
    depth: 1
    dest: Test-Data
    repo: https://github.com/TransparencyToolkit/Test-Data.git
    umask: "0077"

- name: Install DocManager role
  include_role: name=doc_manager allow_duplicates=False

- name: Include ruby role
  include_role: name=our_ruby allow_duplicates=False

- name: Ensure postgresql service has started
  become: true
  service: name=postgresql state=started enabled=yes

  #      - name: Wait for git repositories to sync
  #        retries: 60
  #        delay: 60
  #        until: docmanager.finished and lookingglass.finished and testdata.finished

- name: LG - bundle install
  command: chdir=LookingGlass bash -lc 'bundle install'

- name: LG - change project index to nsadocs
  lineinfile:
    dest: LookingGlass/config/initializers/project_config.rb
    regexp: 'ENV\\[''PROJECT_INDEX''\\] = "archive_test"' # TODO this doesn't work
    line: "ENV['PROJECT_INDEX'] = 'nsadocs'"

- name: Install LG service
  become: true
  template:
    src: lookingglass.service.j2
    dest: /usr/lib/systemd/system/lookingglass.service
    mode: ugo=r


- name: Stop LG systemd service
  become: true
  systemd:
    state: stopped
    daemon_reload: yes
    name: lookingglass

- name: LG - Generate simple form data
  command: chdir=LookingGlass bash -lc 'rails generate simple_form:install --bootstrap'
  # TODO creates?

- name: LG - precompile assets
  command: chdir=LookingGlass bash -lc 'rake assets:precompile'

- name: Ensure LG service has started
  become: true
  service: name=lookingglass state=started enabled=yes
