---
# https://github.com/TransparencyToolkit/IndexServer
# requires curl
#  Ensure curl is installed and that the doc_integrity_check and curb gems are installed.

- name: Fetch IndexServer source code
  register: indexserver
  async: 3600
  poll: 10
  git:
    depth: 1
    dest: IndexServer
    repo: https://github.com/TransparencyToolkit/IndexServer
    umask: "0077"

- name: Install required gems
  command: bash -lc 'gem install doc_integrity_check curb sinatra'

- name: Wait for git repos to sync
  async_status:
    jid: "{{ indexserver.ansible_job_id }}"
  retries: 60
  delay: 60
  until: indexserver.finished

- name: Install IndexServer service
  become: true
  template:
    src: indexserver.service.j2
    dest: /usr/lib/systemd/system/indexserver.service
    mode: ugo=r

- name: Creates indexserver.service.d directory
  become: true
  file: path=/etc/systemd/system/indexserver.service.d/ state=directory

- name: set environment variables in systemd conf
  become: true
  blockinfile:
    create: yes
    mode: ug=r,o=
    dest: /etc/systemd/system/indexserver.service.d/{{ item.name }}.conf
    content: |
      [Service]
      Environment="{{item.name}}={{ item.value }}"
  with_items:
    - {name: 'DOCMANAGER_URL', value: '{{docmanager_url}}' }

- name: Restart IndexServer systemd service
  become: true
  systemd:
    state: restarted
    daemon_reload: yes
    name: indexserver

- name: Ensure IndexServer service has started
  become: true
  service: name=indexserver state=started enabled=yes