---

- name: Fetch ArchiveAdministrator source code
  register: archiveadministrator
  async: 3600
  poll: 5
  git:
    depth: 1
    dest: ArchiveAdministrator
    repo: https://github.com/TransparencyToolkit/ArchiveAdministrator
    umask: "0077" # go= // must be quoted for some reason.
    recursive: no
    track_submodules: no

- name: Install our dependencies from apt
  become: true
  apt:
    state: latest
    install_recommends: no
    cache_valid_time: 7200
    update_cache: yes
    name:
      - sudo # required for 'become'
      - curl # for: rbenv?
      - redis-server
      - libcurl4-openssl-dev # undeclared/missing dependency for curb gem


- name: Install gem dependencies
  become: true
  command: bash -lc 'gem install doc_integrity_check'

- name: Install ArchiveAdministrator service
  become: true
  template:
    src: archiveadministrator.service.j2
    dest: /lib/systemd/system/archiveadministrator.service
    mode: 0444 # ugo=r

- name: Creates archiveadministrator.service.d directory
  become: true
  file: path=/etc/systemd/system/archiveadministrator.service.d/ state=directory

- name: set environment variables in systemd conf
  become: true
  blockinfile:
    create: yes
    mode: 0440 #ug=r,o=
    dest: /etc/systemd/system/docupload.service.d/{{ item.name }}.conf
    content: |
      [Service]
      Environment="{{item.name}}={{ item.value }}"
  with_items:
    - {name: 'ARCHIVE_CONFIG_PATH', value: '{{archive_config_path}}' }
    - {name: 'ARCHIVEADMIN_URL', value: '{{archiveadmin_url}}' }
    - {name: 'QUEUE', value: '*' }
    - {name: 'REDIS_URL', value: '{{redis_url}}' }

- name: Wait for git repos to sync
  async_status:
    jid: "{{ archiveadministrator.ansible_job_id }}"
  retries: 600
  delay: 5
  until: archiveadministrator.finished

- name: Restart ArchiveAdministrator systemd service
  become: true
  systemd:
    state: restarted
    daemon_reload: yes
    name: archiveadministrator

- name: Ensure ArchiveAdministrator service has started
  become: true
  service: name=docupload state=restarted enabled=yes