---

- name: Fetch DocUpload source code
  register: docupload
  async: 3600
  poll: 5
  git:
    depth: 1
    dest: DocUpload
    repo: https://github.com/TransparencyToolkit/DocUpload
    umask: "0077"


- name: Install gem dependencies
  become: true
  command: bash -lc 'gem install sinatra pry doc_integrity_check gpgme'

- name: Install DocUpload service
  become: true
  template:
    src: docupload.service.j2
    dest: /usr/lib/systemd/system/docupload.service
    mode: ugo=r

- name: Creates docupload incoming directory
  become: true
  file: path="{{ docupload_tmp }}/" state=directory
    owner="{{ docupload_user }}"
    mode=u=rwx,go=


- name: Creates docupload.service.d directory
  become: true
  file: path=/etc/systemd/system/docupload.service.d/ state=directory

- name: set environment variables in systemd conf
  become: true
  blockinfile:
    create: yes
    mode: ug=r,o=
    dest: /etc/systemd/system/docupload.service.d/{{ item.name }}.conf
    content: |
      [Service]
      Environment="{{item.name}}={{ item.value }}"
  with_items:
    - {name: 'ocrserver_url', value: '{{ocrserver_url}}' }
    - {name: 'gpg_signer', value: '{{gpg_signer}}' }
    - {name: 'gpg_recipient', value: '{{gpg_recipient}}' }
    - {name: 'lookingglass_url', value: '{{lookingglass_url}}' }
    - {name: 'docupload_tmpdir', value: '{{docupload_tmpdir}}'}

- name: Wait for git repos to sync
  async_status:
    jid: "{{ docupload.ansible_job_id }}"
  retries: 600
  delay: 5
  until: docupload.finished

- name: Restart DocUpload systemd service
  become: true
  systemd:
    state: restarted
    daemon_reload: yes
    name: indexserver

- name: Ensure DocUpload service has started
  become: true
  service: name=docupload state=restarted enabled=yes